version: "3"

env:
  OS:
    sh: uname
  # Trim domain suffix from hostname
  HOSTNAME:
    sh: hostname -s
  # MacOS hostname is flapping, so forcefully set the proper one
  HOSTNAME_HACK: '{{ if eq .OS "Darwin" }}bobbery{{ else }}{{ .HOSTNAME }}{{ end }}'

tasks:
  default: task --list
  hostname: echo $HOSTNAME_HACK

  # Nix -----------------------------------------------------------------------

  nix:install:
    desc: Install Nix
    cmd: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

  nix:uninstall:
    desc: Uninstall Nix
    cmd: /nix/nix-installer uninstall

  nix:update:
    aliases: [up]
    desc: Update Nix flake inputs
    cmd: nix flake update --option access-tokens "github.com=$(gh auth token)"

  nix:gc:
    aliases: [gc]
    desc: Remove unused objects from the Nix store
    cmds:
      - nix-collect-garbage --delete-old
      - sudo nix-collect-garbage --delete-old

  nix:gc:tec:
    aliases: [gc:tec]
    desc: Remove unused objects from the Nix store (tec)
    cmds:
      - ssh nixos@tec 'nix-collect-garbage --delete-old'
      - ssh nixos@tec 'sudo nix-collect-garbage --delete-old'

  nix:repl:
    desc: Launch a repl for this Nix flake
    cmds:
      - echo 'To load flake config, type `:lf .#` in the repl'
      - nix repl

  # NixOS ---------------------------------------------------------------------

  nixos:switch:
    desc: Compile and activate NixOS config
    cmd: nixos-rebuild switch --sudo --flake .#$HOSTNAME_HACK

  nixos:switch:tec:
    aliases: [tec]
    desc: Compile and activate NixOS config (tec)
    cmds:
      - rsync --recursive --delete --delete-excluded --exclude='.git/' --exclude='.jj/' --filter='dir-merge,- .gitignore' ./ nixos@tec:~/nix-config-deploy/
      - ssh nixos@tec 'nixos-rebuild switch --sudo --flake ~/nix-config-deploy#tec'

  # Darwin --------------------------------------------------------------------

  darwin:install:
    desc: Install nix-darwin
    cmds:
      - nix build .#darwinConfigurations.$HOSTNAME_HACK.system
      - ./result/sw/bin/darwin-rebuild switch --flake .#$HOSTNAME_HACK

  darwin:switch:
    aliases: [mac, darwin]
    desc: Compile and activate nix-darwin config
    cmd: sudo /run/current-system/sw/bin/darwin-rebuild switch --flake .#$HOSTNAME_HACK

  # Docker Sandboxes ----------------------------------------------------------

  sbx:
    desc: Build and load the Home Manager Docker Sandbox template
    cmds:
      - nix build .#sbx
      - sbx template load result
