set -s escape-time 10 # Low but not 0 so meta keybindings work reliably
set -s set-clipboard on # Propagate clipboard from nested sessions
set -sa terminal-features ",*:hyperlinks"

set -g mouse on
set -g focus-events on
set -g monitor-bell on
set -g display-time 2000
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g set-titles on
set -g set-titles-string "#H"
set -g word-separators " \"',;|()[]{}<>"

# Status line

set -g status-position top
set -g status-justify left
set -g status-style "bg=default,fg=default"
set -g status-left "#{?client_prefix,#[fg=black bg=yellow],#{?pane_synchronized,#[fg=black bg=red],#[fg=black bg=blue]}} #S "
set -g status-left-length 20
set -g status-right "#[fg=black,bg=white] #H "
set -g status-right-length 50

set -g window-status-style "fg=brightwhite,bg=brightblack"
set -g window-status-current-style "fg=black,bg=white,bold"
set -g window-status-bell-style "fg=red,bg=brightblack"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""

# Keybindings

set -g prefix2 M-Space
set -g mode-keys emacs
set -g status-keys emacs

bind -N "Send the prefix2 key" M-Space send-prefix -2
bind -N "Kill the current window" & kill-window
bind -N "Kill the current pane" x kill-pane
bind -N "Split window vertically" '"' split-window -v -c "#{pane_current_path}"
bind -N "Split window horizontally" %  split-window -h -c "#{pane_current_path}"

bind -N "Reload tmux config" r {
  source ~/.config/tmux/tmux.conf
  display "Reloaded tmux config"
}

bind -N "Toggle pane sync" e {
  set -w synchronize-panes
  display "Synchronize panes: #{?pane_synchronized,ON,OFF}"
}

bind -N "Paste local config into remote session" U {
  load-buffer ~/.config/tmux/tmux.conf
  send-keys "cat << 'EOF' | tmux source-file /dev/stdin" Enter
  paste-buffer -p
  send-keys Enter "EOF" Enter
}

bind -N "Copy last command and output" Y {
  copy-mode
  send-keys -X begin-selection
  send-keys -X previous-prompt
  send-keys -X copy-pipe-and-cancel
}

bind -N "Search in buffer" / {
  copy-mode
  command-prompt -i -p "search-up" "send-keys -X search-backward-incremental \"%%%\""
}

bind -T root -N "Suspend prefix key" F1 {
  set -g prefix None
  set -g prefix2 None
  set -g key-table suspended
  display "Prefix key suspended"
}

bind -T suspended -N "Restore prefix key" F1 {
  set -g prefix C-b
  set -g prefix2 M-Space
  set -g key-table root
  display "Prefix key restored"
}
